# Generated by Django 3.0.6 on 2022-03-09 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctorID', models.IntegerField(primary_key=True, serialize=False)),
                ('doctorName', models.CharField(max_length=50)),
                ('doctorAge', models.IntegerField()),
                ('doctorGender', models.CharField(max_length=10)),
                ('doctorAddress', models.CharField(max_length=100)),
                ('doctorPhone', models.CharField(max_length=20)),
                ('doctorEmail', models.CharField(max_length=50)),
                ('doctorPassword', models.CharField(max_length=50)),
                ('doctorSpecialization', models.CharField(max_length=50)),
                ('doctorExperience', models.IntegerField()),
                ('doctorFees', models.IntegerField()),
                ('doctorAvailability', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patiendID', models.IntegerField(primary_key=True, serialize=False)),
                ('patientName', models.CharField(max_length=50)),
                ('patientAge', models.IntegerField()),
                ('patientGender', models.CharField(max_length=10)),
                ('patientPhone', models.CharField(max_length=20)),
                ('patientBloodGroup', models.CharField(max_length=10)),
                ('patientMedicalHistory', models.CharField(max_length=50)),
                ('patientEmergencyContact', models.CharField(max_length=50)),
                ('patientEmergencyPhone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reminders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder', models.CharField(max_length=50)),
                ('remindTimeStamp', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicFuns.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizTimeStamp', models.DateTimeField()),
                ('quizScore', models.IntegerField()),
                ('quizScoreOutOf', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicFuns.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.FileField(upload_to='prescriptions/')),
                ('prescriptionDate', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicFuns.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicFuns.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicFuns.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Memories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.FileField(upload_to='memories/')),
                ('memoryDate', models.DateField()),
                ('peopleInMemory', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicFuns.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(max_length=100)),
                ('gameDate', models.DateField()),
                ('gameScore', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicFuns.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicFuns.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietDetails', models.FileField(upload_to='diet_details/')),
                ('dietDuration', models.DurationField()),
                ('dietFollowup', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicFuns.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='DailyRemarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=100)),
                ('remarkDate', models.DateField()),
                ('remarkFeedback', models.CharField(choices=[('POSTIVE', 'POSITIVE'), ('NEGATIVE', 'NEGATIVE'), ('NEUTRAL', 'NEUTRAL')], max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicFuns.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Caretaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caretakerName', models.CharField(max_length=50)),
                ('caretakerPhone', models.CharField(max_length=20)),
                ('caretakerAddress', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicFuns.Patient')),
            ],
        ),
    ]
