# Generated by Django 3.0.6 on 2022-03-09 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicFuns', '0002_auto_20220309_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminders',
            name='remindTimeStamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 9, 16, 9, 51, 108397)),
        ),
    ]
